name: Nightly Tests

on:
  schedule:
    - cron: "0 5 * * 4"  # cron is UTC, this translates to 10 PM PST Wednesday.
  # This lets us trigger the workflow from a browser.
  workflow_dispatch:

jobs:
  ios-nightly:
    strategy:
      fail-fast: false
      matrix:
        lib: [SalesforceFileLogger, SalesforceHybridSDK]
        ios: [^26, ^18, ^17]
        include:
          - ios: ^26
            xcode: ^26
            macos: macos-26
          - ios: ^18
            xcode: ^16
            macos: macos-15
          - ios: ^17
            xcode: ^16
            macos: macos-15
    uses: ./.github/workflows/reusable-workflow.yaml
    with:
      lib: ${{ matrix.lib }}
      ios: ${{ matrix.ios }}
      xcode: ${{ matrix.xcode }}
      macos: ${{ matrix.macos }}
    secrets: inherit

  hybrid-samples-nightly:
    strategy:
      fail-fast: false
      matrix:
        lib: [AccountEditor, MobileSyncExplorerHybrid]
        ios: [^26, ^18, ^17]
        include:
          - ios: ^26
            xcode: ^26
            macos: macos-26
          - ios: ^18
            xcode: ^16
            macos: macos-15
          - ios: ^17
            xcode: ^16
            macos: macos-15
    uses: ./.github/workflows/reusable-workflow.yaml
    with:
      lib: ${{ matrix.lib }}
      ios: ${{ matrix.ios }}
      xcode: ${{ matrix.xcode }}
      macos: ${{ matrix.macos }}
      action: build
    secrets: inherit